# PostgreSQL version 9.3.5-1
#  
#  Install pg driver
#		gem install pg
#
#	Configure Using Gemfile
#		gem 'pg'
development: &development
  adapter: postgresql
  encoding: unicode
  database: helth_priority_dev
  pool: 5
  username: postgres
  password: root