test: &default

  # Credentials for REST APIs
  client_id: AXAG4RBsLCGmc16h5NWzLzPcr3u4JZys88h6E2WJT7Co6Qv9vP4BZFAk8yW6
  client_secret: EG6KvxAE1zIgbdFx8iCY_C9eU4HsNxvLc8U0jeTj1Acs8xzwXpjyyxArRygC

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

  # verbose_logging: true

development:
  <<: *default

production:
  <<: *default
  mode: live
