# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17a209be93b8874d43f26110d47f89b5a8bb1af274800e74d274a78c5d3015a5dae5cbb03ac1e8d0d2205c791401fec779e0e0204e35f1119a303f958c8ac09f
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://health.empters.com

test:
  secret_key_base: c07d120826af5320fc4fd1f6d3cf44d6d05fd347223154e0f5b52b844342da7250e936067838d3165d6106bf8439db246bf45862fa9bdcd4fa5c4fb4555b37c6
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://health.empters.com

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  app_host: http://healthpriority.co.uk